# Generated by Django 2.0.3 on 2018-04-11 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=550)),
                ('child_Age', models.IntegerField()),
                ('parent_Name', models.CharField(max_length=100)),
                ('child_Name', models.CharField(max_length=100)),
                ('affliction', models.CharField(max_length=100)),
                ('location', models.IntegerField()),
                ('gender', models.CharField(default='Male', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
