# Generated by Django 2.0.3 on 2018-04-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='email',
        ),
        migrations.RemoveField(
            model_name='child',
            name='name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent_Name',
        ),
    ]
