# Generated by Django 2.0.3 on 2018-04-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_auto_20180411_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='child_Age',
            new_name='child_age',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='child_Name',
            new_name='child_name',
        ),
    ]
